palazzem/ha-econnect-alarm

pyproject.toml
tox.ini

- Closes #5 
Ensure that the the project's Python version matches the one used in Home Assistant. To simplify the tooling, `tox` is used to run linting and tests.
n/a
n/a

tools: add `tox` to handle the project test matrix

---

.github/workflows/hassfest.yaml
.pre-commit-config.yaml
custom_components/econnect_alarm/manifest.json

- Closes #17 
Validate the integration using [hassfest Github Action](https://github.com/home-assistant/actions). Through this GitHub actions we're sure the integration supports properly the latest version of Home Assistant.
This test runs on every merge, PR and on a daily basis.
n/a

tools: add `hassfest` GitHub actions to validate the integration

---

.github/workflows/building.yaml
pyproject.toml

- Closes #18 
- Changes the `pyproject.toml` to only add `custom_components/econnect_alarm` package, so that `hatch build` creates an actual release.
- The project now offers a GitHub action that triggers the build and uploads an artifact when a `v*` tag is created.
n/a
n/a

tools: add GitHub actions to automatically build the package on tag version

---

.github/workflows/building.yaml
.github/workflows/linting.yaml
.github/workflows/testing.yaml

n/a
- Fix the builder action names the package with the right version using `hatch version`
- Update all GitHub actions to `ubuntu-latest`
n/a
n/a

fix(ci): builder action names the package with the right version using `hatch version`

---

custom_components/econnect_alarm/__init__.py
custom_components/econnect_alarm/devices.py
custom_components/econnect_alarm/manifest.json
pyproject.toml
tests/conftest.py
tests/fixtures/responses.py
tests/hass/common.py
tests/test_devices.py

- Closes #27 
Add `AlarmDevice` component to handle main unit states. This is a follow-up PR after it has been removed from `econnect-python` through PR (https://github.com/palazzem/econnect-python/pull/113)
`devices.py` is fully tested with a fake `client` that behaves like the original client. The client isn't a mock, only its responses are mocks.
n/a

feat: add `AlarmDevice` component

---

custom_components/econnect_alarm/helpers.py
tests/test_helpers.py

n/a
When users configure an alarm mode (e.g. VACATION), now they can remove the configuration to disable this mode.
n/a
n/a

fix(config): allow users to remove configuration for alarm modes

---

.github/workflows/building.yaml
pyproject.toml

- Closes #37 
Extend `hatch` builder with `zipped-directory` plugin, so that the release runner can ship a ZIP package. To build a new package simply:
```
$ hatch -v build -t zipped-directory
```
`sdist` target is still needed to build a package that can be installed through `pip`.
n/a
n/a

fix(build): build runner ships a `zip` package instead of a `tar.gz`

---

README.md
custom_components/econnect_alarm/translations/en.json
custom_components/econnect_alarm/translations/it.json

- Closes #41 
Adds a better explanation in the `README.md` and in the UI to better understand what we should put in `domain` during the installation process.
n/a
n/a

docs: update documentation and UI to explain what to put in `domain`

---

custom_components/elmo_iess_alarm/helpers.py
pyproject.toml
tests/test_helpers.py

- Follow-up for PR #49 (cc @xtimmy86x )
Use HA public util `slugify()` to generate the entity name. The previous approach was working properly, even though it was relying on an internal mechanic where the entity name is normalized and then used as `entity_id`.
With this change we're explicit in how the format is.
Add testing to ensure we don't have `__` (as it happens in snake-case) when there is a space in the name.
n/a

refactor: use slugify function to generate the entity name as HA expects

---

custom_components/elmo_iess_alarm/alarm_control_panel.py
custom_components/elmo_iess_alarm/binary_sensor.py
custom_components/elmo_iess_alarm/helpers.py
tests/conftest.py
tests/test_alarm_panel.py
tests/test_binary_sensors.py
tests/test_helpers.py

- #53 
This change ensures that the self-generated `entity_id` is a valid HA Entity ID, while keeping the name in a human readable format. The validation is done via tests using `valid_entity_id()` HA core function and is not validated at runtime (there is no reasons to do that live).
Even if the integration was working properly, entities were not respecting the official `entity_id` format: `<domain>.<entity_id>`. With this change, `domain` is included in the Entity ID even though it is remove by HA for unclear reasons. This behavior is described in the official documentation: https://www.home-assistant.io/faq/unique_id/#can-be-changed
Before:
After:
Install the integration before the change and after the change. If `name` is not set with a "friendly name", you should see this change.
n/a

feat!: binary sensors and control panels generates a valid Entity ID with a human readable name

---

custom_components/elmo_iess_alarm/__init__.py
custom_components/elmo_iess_alarm/config_flow.py
custom_components/elmo_iess_alarm/const.py
custom_components/elmo_iess_alarm/strings.json
custom_components/elmo_iess_alarm/translations/en.json
custom_components/elmo_iess_alarm/translations/it.json

- Closes #23 
This change introduces a new optional variable `SCAN_INTERVAL` that let users to change how often the system is updated. This closes the high data usage issue as there is no other way, at the time of writing, to handle this specific case.
Open the integration configuration page and set a scan interval.
Unfortunately, this solution is suboptimal. Currently the system works that way:
1. The system and the cloud don't communicate often with a very minimum data consumption
2. When any system (mobile app, webapp or this integration) asks for a status update (poll), the cloud forces the system to provide the latest update
3. As this integration provides real-time updates, the default scan interval asks for the update every 5 seconds with a long-polling that lasts 15 seconds.
4. …

feat(collector): support configurable scan interval to reduce data usage

---

custom_components/elmo_iess_alarm/binary_sensor.py
custom_components/elmo_iess_alarm/devices.py
custom_components/elmo_iess_alarm/manifest.json
custom_components/elmo_iess_alarm/strings.json
custom_components/elmo_iess_alarm/translations/en.json
custom_components/elmo_iess_alarm/translations/it.json
pyproject.toml
tests/conftest.py
tests/fixtures/responses.py
tests/test_binary_sensors.py
tests/test_devices.py

- Closes #36 
This change leverages `econnect-python` to retrieve the system global state. It includes a list of errors, anomalies and triggered input/output so that you can build automations on top of it. The following is a list of generated entities:
```
binary_sensor.anomalies_led
binary_sensor.inputs_led
binary_sensor.alarm_led
binary_sensor.tamper_led
binary_sensor.has_anomaly
binary_sensor.panel_tamper
binary_sensor.panel_no_power
binary_sensor.panel_low_battery
binary_sensor.gsm_anomaly
binary_sensor.gsm_low_balance
binary_sensor.pstn_anomaly
binary_sensor.system_test
binary_sensor.module_registration
binary_sensor.rf_interference
binary_sensor.input_failure
binary_sensor.input_alarm
binary_sensor.input_bypass
binary_sensor.input_low_battery
binary_sensor.input_no_supervision …
```

feat: add system global states to monitor the central unit

---

.github/workflows/building.yaml
.github/workflows/publish.yaml

n/a
In this update, we've refined our CI/CD process. Rather than uploading an artifact during the `building` workflow, we now upload the package directly to the release when it's triggered. This ensures that the `building` workflow remains focused solely on verifying the integrity and success of the build step.
n/a
n/a

ci(release): all packages are built during the release action

---

custom_components/econnect_metronet/binary_sensor.py
tests/conftest.py
tests/test_binary_sensors.py

Create binary_sensor only for configured sectors #59
Separate the `EconnectDoorWindowSensor` class into 2 class named `InputSensor` and `SectorSensor` for decrease the number of if statements

refactor: split binary sensors in their own entities

---

custom_components/econnect_metronet/__init__.py
custom_components/econnect_metronet/coordinator.py
custom_components/econnect_metronet/devices.py
pyproject.toml
tests/conftest.py
tests/test_coordinator.py
tests/test_devices.py

- Closes #51 
This change forces a full update when `UpdateFailed` exception is detected. If that happens, very likely there is a connectivity error and there is a chance the backend considers the connection with the central unit gone. In that case, it resets last known IDs, causing the integration to not detect any new change as described in #51.
This fix is available in this commit: https://github.com/palazzem/ha-econnect-alarm/pull/68/commits/588082b455c8e005c290dce3b6c66eaf649e70b3
Instead of adding the fix, this PR also refactors entirely how the `DataUpdateCoordinator` is exposed to the integration, so that now it's a self contained coordinator called `AlarmCoordinator`. The coordinator is fully tested and a regression test is added to the test suite.
- Install the latest version …

fix(collector): force update when connection is unstable

---

custom_components/econnect_metronet/__init__.py
custom_components/econnect_metronet/coordinator.py
custom_components/econnect_metronet/devices.py
pyproject.toml
tests/conftest.py
tests/test_coordinator.py
tests/test_devices.py

- Follow-up for #51 
This change refactors entirely how the `DataUpdateCoordinator` is exposed to the integration. Instead of writing the fetching logic inside the `async_setup_entry` as a standalone function, we moved the entire logic in a dedicated class that is easy to test. `AlarmCoordinator` is fully tested and a regression test is added to the test suite.
Furthermore, the integration now uses `async_config_entry_first_refresh()` to call the first update, so that if there are issues with the update, the integration will raise `ConfigEntryNotReady` exception, preventing the integration from loading. At that stage, the integration is flagged as "Failed to load", preventing logs spamming.
- Install the integration
- It should work as usual as this is just a refactoring
n/a

refactor: create `AlarmCoordinator` to separate HA functions from the fetching logic

---

.github/workflows/building.yaml
.github/workflows/hassfest.yaml
.github/workflows/linting.yaml
.github/workflows/publish.yaml
.github/workflows/testing.yaml
pyproject.toml

- Closes #75 
- Closes #77 
This change updates our CI release process so that:
- Only HACS packages are uploaded as release assets (this fixes users' issues).
- Removes the Hatch ZIP plugin as the ZIP package is not needed anymore.
- Builder workflow now runs at every PR and push to verify the package is installable.
Run the CI.
n/a

fix: build system uploads only HACS files to prevent downloading errors

---

tests/conftest.py
tests/test_binary_sensors.py

This PR make the alarm_device in tests to auto-initialize for connecting and updating data

feat: auto-initialize tests alarm_device

---

.gitignore
custom_components/econnect_metronet/__init__.py
custom_components/econnect_metronet/binary_sensor.py
tests/conftest.py
tests/test_experiments.py

n/a
This change introduces the concept of having experimental settings in the YAML configuration. YAML configurations are not meant to be used by integrations, which should use always the configuration flow.
In that case, we use a not suggested method to provide settings we don't want to expose easily to end users. In this way we can ship settings we can add/remove/break based on the need.
With this change you can force HA to update sensors data even if previous/actual states are the same.
Update your `configuration.yaml` with the following code:
```yaml
econnect_metronet:
force_update: true
```
n/a

feat(experimental): add `force_update` as experimental setting in YAML conf

---

custom_components/econnect_metronet/binary_sensor.py
custom_components/econnect_metronet/const.py
tests/test_experimental_settings.py

- Follow-up for #85 
Update the experimental configuration under `experimental` key.
```yaml
econnect_metronet:
experimental:
force_update: true
```
n/a

fix(experimental): namespace experimental settings under `experimental` key

---

custom_components/econnect_metronet/binary_sensor.py
custom_components/econnect_metronet/devices.py
tests/test_binary_sensors.py
tests/test_devices.py

Create InputSensors from _inventory query and use new get_status function for rendering the is_on state

feat: create InputSensors with _inventory

---

custom_components/econnect_metronet/binary_sensor.py
tests/test_binary_sensors.py

Change how is generated the uniqueID for Alerts and revert to old method for backward compatibility

fix: restore previous unique id structure in `AlertSensor`

---

custom_components/econnect_metronet/devices.py
custom_components/econnect_metronet/manifest.json
pyproject.toml
tests/test_devices.py

Implement the functionality to read and store the latest alert IDs for efficiently polling updates

fix: read alerts last ids for polling

---

custom_components/econnect_metronet/__init__.py
custom_components/econnect_metronet/binary_sensor.py
custom_components/econnect_metronet/sensor.py
custom_components/econnect_metronet/translations/en.json
custom_components/econnect_metronet/translations/it.json
tests/test_binary_sensors.py
tests/test_experimental_settings.py
tests/test_sensors.py

- Closes #81 
Transform alarm_led, tamper_led and inputs_led in sensor with a text translated reported status
0: No Alarm
1: Memory Alarm
2: Alarm
Based on the original user manual specification:
New sensors are rapresented like this:
Individual sensor history is represented like this

feat!: treat alarm_led, tamper_led and inputs_led as sensors

---

tests/conftest.py

- Closes #103 
After the change in `responses` 0.24.0 (https://github.com/getsentry/responses/pull/685/) all tests fail as `socket.socket` is accessed within the library. This change uses `socket_enabled` fixture from `pytest-socket` library so that any time an `ElmoClient` fixture is used, sockets are enabled.
This change should not have negative impacts as `responses` is still not making any call to external services.
Run any test that access `client` fixture.
n/a

tests: enable socket access for `responses` 0.24+ compatibility

---

custom_components/econnect_metronet/config_flow.py
custom_components/econnect_metronet/helpers.py
tests/helpers.py
tests/test_config_flow.py

n/a
This change improves the testing in the following areas:
1. Removes `validate_credentials` as it was a level of indirection. This makes testing straightforward as we don't need to test any helper.
2. Adds `_()` test helper that makes mocking easier with long python paths.
3. Refactors `ConfigFlow` tests so that they use `pytest-mock` properly.
4. Fixes `pytest-mock` by removing context managers as they are not needed.
n/a
n/a

tests(config_flow): add coverage for config exceptions; refactor `ConfigFlow` tests

---

.pre-commit-config.yaml
tests/conftest.py
tests/helpers.py

n/a
Instead of using our own `MockConfigEntry`, we're using the one provided directly from HA. It behaves exactly as the original one, with the only difference that we remove the `MappingProxyType` mapping (read-only protection) as we want to override values during tests.
This change is required to use `config_entry` fixture while testing our `OptionsFlow`.
n/a
n/a

tests: replace custom MockConfigEntry with the official `hass.MockConfigEntry`

---

tests/test_options_flow.py

n/a
Adds partial coverage for the integration `OptionsFlow`. The goal is to have a very simple set of tests that can be expanded while working on #60.
n/a
The change in #60 will complete the module coverage.

tests: add OptionsFlow tests (partial coverage)

---

custom_components/econnect_metronet/__init__.py
custom_components/econnect_metronet/config_flow.py
custom_components/econnect_metronet/devices.py
custom_components/econnect_metronet/exceptions.py
custom_components/econnect_metronet/helpers.py
custom_components/econnect_metronet/translations/en.json
custom_components/econnect_metronet/translations/it.json
tests/test_devices.py
tests/test_helpers.py
tests/test_migrations.py
tests/test_options_flow.py

Closes #60 
Transform the configuration of sectors in the options flow from textual input to a multi-select interface for a better and more user-friendly experience:
- Add `select` component for the `OptionsFlow`
- Include migration between options v2 -> v3 to avoid breaking changes
- Remove `parse_areas_config` utility as validation is handled in the `select` component
Old method:
New method:

refactor: use multi select in setup options

---

custom_components/econnect_metronet/alarm_control_panel.py
custom_components/econnect_metronet/config_flow.py
custom_components/econnect_metronet/const.py
custom_components/econnect_metronet/devices.py
custom_components/econnect_metronet/strings.json
custom_components/econnect_metronet/translations/en.json
custom_components/econnect_metronet/translations/it.json
tests/conftest.py
tests/test_alarm_panel.py
tests/test_decorators.py
tests/test_devices.py
tests/test_options_flow.py

- Closes #96 
Adds arm AWAY configuration in the `OptionsFlow` step with the following logic:
- After version update, the setting is empty
- If the setting is not set (empty), the device arms all sectors (backward compatibility)
- If the setting is set, only selected sectors are armed
1. Arming the system without setting the option should arm all sectors
2. Arming the system with the option set, should arm only selected sectors
n/a

feat: add AWAY state configuration

---

.gitignore
README.md
compose.yaml

n/a
Provides a Docker container defined in a `compose.yaml`, to spin up a Home Assistant stable version where developers can test their changes. This method is optional, so developers can still test the way they want their changes.
Start the container through `docker compose up -d` and install the integration as you would normally do.
n/a

feat: provide HA instance via `compose.yaml`

---

custom_components/econnect_metronet/manifest.json
pyproject.toml

- Closes https://github.com/palazzem/ha-econnect-alarm/issues/115
This update refines the `query()` method in the client, which fetches synchronized data between the main unit and the cloud (using `_get_descriptions()` under the hood). Issues arise when strings are not in sync, specifically when:
1. The central unit has defined and `InUse` outputs, inputs, or sectors.
2. The cloud is not in sync, leading to missing keys (9, 10, or 12) in `_get_descriptions()`, causing a `KeyError`.
To address this, we've implemented a safer access via the dictionary `get()` method. Now, if a string is missing, `Unknown` is returned instead of an error.
Test with a central unit where an output is `InUse`, but no strings are configured in the cloud.
n/a

deps: update econnect-python to 0.9.1

---

pyproject.toml

n/a
Includes `async_timeout` in the dependency list. This dependency is automatically included in Home Assistant, but as this project is a standalone project, this dependency is required.
n/a
n/a

deps: add `async_timeout` package used in the `AlarmCoordinator`

---

README.md
custom_components/econnect_metronet/manifest.json

- Closes #122 
Adds `econnect-python` logger (`elmo`) to the integration `manifest.json` so that all loggers can be enabled directly from the UI.
Activate it from the Integration configuration page:
n/a

fix: `econnect-python` logger can be enabled from UI

---

README.md
custom_components/econnect_metronet/config_flow.py
custom_components/econnect_metronet/strings.json
custom_components/econnect_metronet/translations/en.json
custom_components/econnect_metronet/translations/it.json
tests/test_config_flow.py

- Closes #119 
Makes `domain` required during the installation step, forcing users to insert a value. By default, the field is prefilled with `default` that should work for all users without a vendor.
Install the integration and check the installation page.
n/a

fix(config): `domain` field is required and pre-filled with `default`

---

custom_components/econnect_metronet/coordinator.py

- #121 
Changes debug level from `ERROR` to `DEBUG` when a full update is required.
n/a
This partially solves the issue in #121 where, in some cases, sensors can still be detected as unavailable. For further improvements, we should rewrite the `AlarmCoordinator` logic as  we may need to handle updates differently.

fix(log): forcing a full update is not considered an error

---

custom_components/econnect_metronet/__init__.py

- Closes #19 
Sets `CONFIG_SCHEMA` to accept configuration from config entries. This change is not tested as `hassfest` workflow does the check to be sure it's set.
n/a
n/a

fix: set `CONFIG_SCHEMA` to accept configuration from config entries

---

custom_components/econnect_metronet/devices.py
tests/test_devices.py

- Closes #123 
Instead of disarming all sectors, the `AlarmDevice` disarms only the currently activated sector. This change is a no-op for users as it is expected that disarming activated sectors is the same as disarming all. Instead, it's a fix for all users that have accounts with limited permissions and multiple areas, that can't use the disarm all (see #123).
A race condition may be introduced with this change if:
- Sectors 1, 2 are activated
- The device updates the internal state and 1, 2 are now considered activated
- From an external tool (e.g. BrowserOne or web UI) we enable also sector 3
- We immediately disarm the system before the device updates the internal state
This race condition is an edge case that we consider negligible as it requires too many steps. Furthermore, the …

fix(device): disarm only currently activated sectors to support users with limited permissions

---

custom_components/econnect_metronet/__init__.py

- #19 
- #131
The change made in #131 temporarily disabled `experimental` settings in the `configurations.yaml`. With this change we enable them again. We also remember that experimental settings are an internal API and such keys will be removed without notice. Indeed, Home Assistant discourages integrations to use YAML configurations, hence why users should not use these.
n/a
n/a

fix(config): `experimental` settings are enabled again as internal config

---

custom_components/econnect_metronet/__init__.py
custom_components/econnect_metronet/binary_sensor.py
custom_components/econnect_metronet/const.py
custom_components/econnect_metronet/devices.py
custom_components/econnect_metronet/services.py
custom_components/econnect_metronet/services.yaml
tests/test_binary_sensors.py
tests/test_devices.py
tests/test_services.py

n/a
Implements `arm_sectors` and `disarm_sectors` services that can be used to enable a single sector or a list of sectors. The change includes an internal mapping between sectors entity ids and the actual sector ID in the e-Connect backend API. While this change is not expected to stay, it is currently required as Home Assistant doesn't provide a way to easily access entities (see https://github.com/palazzem/ha-econnect-alarm/commit/b16d1190771ccef5b301cf11bab75329d7057ce2#diff-9228969e4ac379606b6ced4a4f29bcacc8c5cf55b2a94c47721038593dab9557R11-R23).
Open the developer console and simply activate/deactivate sectors (or use it within automations).
A refactoring of `AlarmDevice` is required regardless, so we don't need to overcomplicate this implementation as interfaces will change …

feat: add arm/disarm sectors services to activate/deactivate a selection of sectors

---

custom_components/econnect_metronet/icons.json

- Related to #144 
Add missing icons for registered services:
n/a
n/a

fix: add missing icons for registered services

---

custom_components/econnect_metronet/__init__.py
custom_components/econnect_metronet/const.py
custom_components/econnect_metronet/devices.py
tests/test_devices.py

n/a
Provides an internal configuration to manage only a subset of possible sectors. This is useful if the alarm panel should not take into consideration some sectors, meaning it will consider itself "Disarmed" even if some sectors are activated.
**WARNING**: This change is `experimental`, meaning it will be removed without deprecation notice.
Add the following to your `configuration.yaml`:
```yaml
econnect_metronet:
experimental:
managed_sectors: [1, 2, 4]
```
Note that `[1, 2, 4]` must always be a list, and it must match the number of your sectors. An empty list, or a missing configuration, means that all sectors are managed.
Add the configuration as described above. You should see some sectors "Unavailable".
n/a

feat(experimental): add managed sectors to control only part of available areas

---

tests/conftest.py

- Closes #134 
Overrides `pytest_configure()` that is defined in HA fixtures.
If a test fails, DEBUG logs should not be printed.
n/a

tests: disable DEBUG log level when `pytest` is launched with `--verbose`

---

custom_components/econnect_metronet/coordinator.py
custom_components/econnect_metronet/devices.py
custom_components/econnect_metronet/manifest.json
pyproject.toml
tests/test_coordinator.py
tests/test_devices.py

- Fixes #148 
**Context:** This update enhances the `AlarmCoordinator` by enabling it to handle device disconnections during state polling and updates more gracefully. 
**Problem Solved:** Previously, a device disconnection led to all binary sensors entering an "Unavailable" state, potentially triggering undesired automations, including false alarm activations. To mitigate this, the update allows the `AlarmCoordinator` to retain the device's last known state instead of defaulting to "Unavailable" during brief disconnections.
**Implementation Details:** 
- The `AlarmDevice` now monitors the connection status through a new `device.connected` attribute. 
- This attribute is automatically refreshed once the device reconnects, ensuring the system accurately reflects the current state.
- …

fix(collector): return previous states when the device is disconnected

---

custom_components/econnect_metronet/binary_sensor.py
custom_components/econnect_metronet/devices.py
custom_components/econnect_metronet/strings.json
custom_components/econnect_metronet/translations/en.json
custom_components/econnect_metronet/translations/it.json
tests/test_binary_sensors.py

- Closes #139 
This change adds a binary sensor as a feedback mechanism in case the device is not connected to the Cloud API. You can use it to know if the state that you see is up to date, to trigger automations, to send notifications.
**Example:**
1. Add the binary sensor to your dashboard.
2. The sensor should be `off` in case of connection.
3. Disconnect your main unit (device).
4. The sensor should be triggered.
This is a follow-up PR for #148. With both changes, we keep the previous state in case of disconnection to avoid triggering unwanted automations, but at the same time we provide a good feedback mechanism.

feat(entity): add connection status binary sensor to provide feedback in case of a disconnection

---

custom_components/econnect_metronet/devices.py
tests/test_devices.py

- Follow-up #150 
- Closes #148 
This change handles updates when a connection reset happens. In that case, the `last_id` is equal 1, meaning the Cloud API returns an empty state. With this change such updates are discarded and a full update is forced to reconcile the actual (cached) state, with the real one. 
1. Activate at least one sector
2. Disconnect the main unit
3. Wait the Integration to use a cached state (you should see errors in logs)
4. Reconnect the main unit
5. The integration must not change the alarm state (if the bug is present, it will go in "Disarmed" and then back to the actual state).
n/a

fix(device): discard Cloud APIs empty states (connection resets)

---

custom_components/econnect_metronet/__init__.py
tests/conftest.py
tests/helpers.py
tests/test_alarm_panel.py
tests/test_binary_sensors.py
tests/test_helpers.py
tests/test_migrations.py
tests/test_sensors.py
tests/test_switch.py

- Closes #156 
Config entries are updated using `async_update_entry` instead of using config attributes directly. In particular:
- Migrations don't use `config.version = 2` anymore
- Tests don't use a custom `MockConfigEntry` mock, in favor of the one provided by `hass.fixtures` (original HA fixtures)
- All tests are updated to use both the `MockConfigEntry` and `async_update_entry`
n/a
n/a

fix(deprecation): use `async_update_entry` when handling config entries

---

custom_components/econnect_metronet/devices.py
tests/test_devices.py

- Closes #154 
This change fixes a race condition that happens when the device arms the system, but before this happens an update is triggered and brings the system to a wrong state. Furthermore, avoids the `AlarmDevice` to set "Arm Away" wrong state.
From "disarm", trigger the "arm home" state and be sure it doesn't transition back to "disarm", or in a wrong "arm away" state.
This change creates a dependency between the `AlarmDevice` and the arm/disarm caller as it is expected who calls one of these methods, to set the right ending state. While this is not great and would be better to decouple it, it's a good enough solution. At some point, we may want to remove `AlarmDevice` transforming it in an actual entity.

fix(device): avoid state update while arming or disarming

---

.github/workflows/building.yaml
.github/workflows/linting.yaml
.github/workflows/testing.yaml
tox.ini

- Closes #152 
Changes the test matrix to support the following Python versions:
- 3.11 (Home Assistant version < 2024.4)
- 3.12 (Home Assistant version 2024.4+)
Run the testing matrix:
```bash
tox
```
n/a

feat: add support for Python 3.12

---

tox.ini

- n/a
Locally, Python 3.11 tests were skipped as `py3.11` executable is not found. This change uses the right python executable name (`python3.11`).
n/a
n/a

test(tox): use the right Python executable in tox configuration

---

custom_components/econnect_metronet/services.py

- n/a
Removes `code` from debug logs, to prevent credentials leak.
n/a
n/a

fix(log): remove `code` from services debug logs

---

custom_components/econnect_metronet/alarm_control_panel.py
custom_components/econnect_metronet/decorators.py
custom_components/econnect_metronet/services.py

- Closes #117 
This change retries all decorated function call or services after obtaining a new refreshed token, if necessary. These decorators have been applied to all calls made by the Alarm Panel and Services.
The set state decorator now handles all exceptions so that, in case of unexpected failure, the previous state is always reverted.
1. Enable a long delay (e.g. 3600s)
2. Wait for 5 minutes (token expiration)
3. Run any action from the panel or call an arm/disarm service
This change doesn't have unit tests, hence why the code coverage decreased. While this is very sub-optimal for the code quality and reliability, we're working on the underlying implementation refactoring as the retry mechanism must be moved in `econnect-python`. This is necessary otherwise all library users have …

fix(entity): retry all calls while refreshing the access token if expired

---

custom_components/econnect_metronet/__init__.py
custom_components/econnect_metronet/icons.json
custom_components/econnect_metronet/services.py
custom_components/econnect_metronet/services.yaml
tests/test_services.py

- Closes #160 
Add `update_state` service so that users can trigger a full update manually (through lovelace dashboard) or programmatically (through automations).
Add a button in the Lovelace dashboard as follows:
1. Add a card of type "button".
2. In "Entity", select your Alarm Panel.
3. In "Tap Action", select "Call Service".
4. In "Service", select "e-Connect/Metronet Alarm: Update Alarm State".
5. Click "Save".
The screenshot below is a configuration example; update it based on your needs:
Trigger `update_state` service.
n/a

feat(service): add `update_state` service to force alarm updates

---

custom_components/econnect_metronet/manifest.json
pyproject.toml

- Fixes #180 
This change updates `econnect-python` library with version `0.14.0`. Changes that are fixing the underlying problem of the integration are:
* Sectors, inputs and outputs `last_id` values are retrieved properly (https://github.com/palazzem/econnect-python/pull/156)
* Use e-Connect web login to register clients with Cloud API long-polling (https://github.com/palazzem/econnect-python/pull/161)
* Use web login access token when `Redirect` URL is followed, keeping long-polling active (https://github.com/palazzem/econnect-python/pull/163)
Full release notes are available here: https://github.com/palazzem/econnect-python/releases/tag/v0.14.0
n/a
n/a

fix(client): update `econnect-python` to support backend long-polling

---

custom_components/econnect_metronet/helpers.py
tests/test_devices.py
tests/test_helpers.py

- Fixes #176 
Recent firmware updates to the central unit allow user identification based on inserted PIN, even if the `user_id` is not explicitly provided. Since this lookup is now handled internally by the unit, specifying a combined `<USER_ID><CODE>` is no longer necessary. By default, the system can safely assume `user_id = "1"` when it's omitted.
Arm or disarm the alarm without selecting your `<USER_ID>`.
n/a

fix(entity): `split_code` returns a `user_id=1` if the code is lesser than 7 digits
