- README.md
- Closes #7 
Includes in the `README.md` how to install this integration.
n/a
This documentation is good enough for people to install this integration manually. Future PRs will improve it further.
> docs: add installation docs to README

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- Closes #4 
Includes GitHub templates for:
- GitHub issues page
- Bug reports
- Feature requests
- Pull requests
n/a
n/a
> tools: add GitHub templates for bug reporting / features / pull requests

- CONTRIBUTING.md
- Closes #3 
Add `CONTRIBUTING.md` to describe our contribution guidelines.
n/a
n/a
> feat: add contribution guidelines

- .github/workflows/linting.yaml
- .github/workflows/testing.yaml
- README.md
- Closes #8
Provides GitHub actions for:
- Testing
- Linting
- Code coverage (via Coveralls)
CI runs at every PR and after merging to the `main` branch.
n/a
> tools: add GitHub actions to provide CI for linting, testing and code coverage

- custom_components/econnect_alarm/manifest.json
> release: build version 0.2.0

- .github/workflows/publish.yaml
- README.md
- hacs.json
- Closes #30 
I created a basic hacs.json file in the root folder and a small modification to the build and release workflow to create and publish a zip file tied to any tagged release.
After publishing several releases on my repo I manually added it to the HACS "custom repositories" and installed it on my system where it worked as expected.
This will make installing and updating the component much easier for any HACS user.
Once it will be used and tested by enough people it could be worthy asking to be added to the "main" HACS repo list.
> feat: HACS installation support

- custom_components/econnect_alarm/translations/it.json
- Closes #40 
Add `IT` translation.
Load the integration and use Italian language.
n/a
> feat: add IT translation

- README.md
- custom_components/elmo_iess_alarm/config_flow.py
- custom_components/elmo_iess_alarm/strings.json
- custom_components/elmo_iess_alarm/translations/en.json
- custom_components/elmo_iess_alarm/translations/it.json
- tests/test_config_flow.py
n/a
Update outdated docs with the latest screenshots.
n/a
n/a
> docs: update Elmo/IESS references with the latest screenshots

- README.md
- Follow-up for #56 
- Related to #55 
Improved section.
n/a
n/a
> docs: improve `homekit` section

- custom_components/econnect_metronet/devices.py
- tests/test_devices.py
#59 
Add a property called _inventory in the AlarmDevice class for storing the data of inputs, sectors and alerts
and call the update function for update his value
> refactor: add _inventory in AlarmDevice

- custom_components/econnect_metronet/__init__.py
- custom_components/econnect_metronet/devices.py
- tests/test_devices.py
- Closes #51 
This change forces a full update when the last update failed. If that happens, very likely there is a connectivity error and there is a chance the backend considers the connection with the central unit gone. In that case, it resets last known IDs, causing the integration to not detect any new change as described in #51.
- Install the latest version that includes this change
- Produce updates for 1-2 minutes (e.g. trigger some inputs)
- **Test 1:** disconnect the central unit and reconnect immediately
- The integration is stuck, it should recover within 5 minutes
- Produce updates for 1-2 minutes (e.g. trigger some inputs)
- **Test 2:** disconnect the central unit and reconnect after 5-10 minutes
- The integration is stuck, it should recover within 5 minutes
n/a
> fix(collector): force an update when the integration fails an update

- tests/conftest.py
- tests/fixtures/responses.py
- tests/test_binary_sensors.py
Added missing tests for binary_sensors.py
> feat: add missing tests for binarysensors

- README.md
- pyproject.toml
- tox.ini
n/a
Use `lcov` exporter to align coveralls coverage with reality.
Check coveralls build.
n/a
> ci: write xml code coverage for better coveralls support

- custom_components/econnect_metronet/manifest.json
- pyproject.toml
n/a
Update `econnect-python` to version 0.8.0.
n/a
n/a
> deps: update econnect-python to 0.8.0

- custom_components/econnect_metronet/manifest.json
- pyproject.toml
n/a
Update `econnect-python` to a stable version (0.9.0)
n/a
n/a
> deps: update `econnect-python` to version 0.9.0

- .pre-commit-config.yaml
- custom_components/econnect_metronet/__init__.py
- custom_components/econnect_metronet/alarm_control_panel.py
- custom_components/econnect_metronet/binary_sensor.py
- custom_components/econnect_metronet/const.py
- custom_components/econnect_metronet/decorators.py
- custom_components/econnect_metronet/sensor.py
- tests/fixtures/responses.py
n/a
Update `pre-commit` hooks and apply the latest `black==24.x` changes.
n/a
n/a
> refactor: update `pre-commit` hooks

- custom_components/econnect_metronet/alarm_control_panel.py
- Closed #120 
Replace all constants marked as deprecated and that will be removed in Home Assistant version 2025.1.
n/a
n/a
> fix(deprecation): replace constants deprecated in future versions of HA (2025.1)

- custom_components/econnect_metronet/manifest.json
- pyproject.toml
- Closes #112 
Updates `econnect-python` package to version 0.10.0.
n/a
n/a
> deps: update `econnect-python` to version 0.10.0

- custom_components/econnect_metronet/devices.py
- Closes #112
Catches all `CommandError` exceptions when the integration fails in changing the main unit state.
n/a
n/a
> feat: catch `CommandError` exceptions

- custom_components/econnect_metronet/manifest.json
- pyproject.toml
- n/a
Updates `econnect-python` dependency to the latest stable (0.12.0)
n/a
n/a
> deps: update `econnect-python` version 0.12.0

- .github/workflows/building.yaml
- .github/workflows/linting.yaml
- .github/workflows/testing.yaml
- tests/test_services.py
- tox.ini
n/a
Update services tests so they are compatible with the latest HA 2025.4.x fixtures.
n/a
n/a
> tests: compatibility for Home Assistant >= 2025.4

- pyproject.toml
n/a
Add Python 3.13 classifier as we follow Home Assistant Python support.
n/a
n/a
> feat(package): use Python 3.13 classifier

- custom_components/econnect_metronet/manifest.json
- pyproject.toml
- Fixes #186 
This change updates `econnect-python` to version 0.14.1. This version includes a fix that restores support for long-polling in IESS. Check the full changeset at: https://github.com/palazzem/econnect-python/releases/tag/v0.14.1
n/a
n/a
> fix(client): update `econnect-python` to support backend long-polling in IESS
